'use client';

import React, { useCallback, useEffect, useId, useRef, useState } from 'react';
import Link from 'next/link';
import { AppEmptyState } from '@/components/empty-state/AppEmptyState';
import { EvidenceArtifactViewer } from './EvidenceArtifactViewer';
import { RedactionControls } from './RedactionControls';
import { getAppUserRole, getSampleVerificationText, isOperationsRole } from '@/lib/app-role';
import { startEvidenceVerification, VerificationApiError } from '@/lib/verification-api';
import type {
    PiiDetectionResult,
    ValidationErrors,
    VerificationResult,
    VerificationStep,
} from '@/types/verification';
import type {
    EvidenceArtifact,
    RedactionRegion,
    RedactionTool,
    RedactionLevel,
    ViewingPermission,
} from '@/types/evidence-artifact';

/* ─── Accepted image MIME types ─────────────────────────────────────────── */

const ACCEPTED_MIME_TYPES = ['image/png', 'image/jpeg', 'image/webp'] as const;
const ACCEPTED_MIME_SET: ReadonlySet<string> = new Set(ACCEPTED_MIME_TYPES);
const MAX_IMAGE_BYTES = 5 * 1024 * 1024; // 5 MB
const MIN_TEXT_LENGTH = 20;
const ENHANCED_DRAFT_STORAGE_KEY = 'soter.enhanced-verification-flow.draft.v1';

interface EnhancedVerificationDraft {
    textInput: string;
}

export function parseEnhancedVerificationDraft(
    raw: string | null,
): EnhancedVerificationDraft | null {
    if (!raw) return null;
    try {
        const parsed: unknown = JSON.parse(raw);
        if (!parsed || typeof parsed !== 'object') return null;
        const candidate = parsed as Record<string, unknown>;
        if (typeof candidate.textInput !== 'string') return null;
        return { textInput: candidate.textInput };
    } catch {
        return null;
    }
}

function readEnhancedVerificationDraftFromStorage(): EnhancedVerificationDraft | null {
    if (typeof window === 'undefined') return null;
    return parseEnhancedVerificationDraft(
        window.localStorage.getItem(ENHANCED_DRAFT_STORAGE_KEY),
    );
}

/* ─── Enhanced Flow State ─────────────────────────────────────────────── */

interface EnhancedFlowState {
    step: VerificationStep;
    imageFile: File | null;
    textInput: string;
    errors: ValidationErrors;
    apiError: string | null;
    result: VerificationResult | null;
    evidenceArtifact: EvidenceArtifact | null;
    showArtifactViewer: boolean;
}

/* ─── Mock Evidence Artifact Creation ───────────────────────────────────── */

function createMockEvidenceArtifact(
    file: File | null,
    text: string,
    piiDetected: boolean
): EvidenceArtifact {
    const now = new Date();
    const mockPermissions: ViewingPermission = {
        canViewOriginal: true,
        canViewRedacted: true,
        canModifyRedactions: true,
        canApproveRedactions: false,
        role: 'operator',
    };

    const mockArtifact: EvidenceArtifact = {
        id: `artifact-${now.getTime()}`,
        metadata: {
            id: `meta-${now.getTime()}`,
            type: file ? 'image' : 'text',
            filename: file?.name || 'text-evidence.txt',
            mimeType: file?.type || 'text/plain',
            size: file?.size || text.length,
            uploadedAt: now,
            uploadedBy: 'current-user',
            piiDetected,
            piiTypes: piiDetected ? ['email', 'phone'] : [],
        },
        content: file ? URL.createObjectURL(file) : text,
        thumbnail: file ? URL.createObjectURL(file) : undefined,
        redactionState: {
            level: piiDetected ? 'partial' : 'none',
            regions: [],
            autoGeneratedRegions: [],
            manuallyReviewedRegions: [],
            lastModified: now,
            modifiedBy: 'current-user',
        },
        permissions: mockPermissions,
    };

    return mockArtifact;
}

/* ─── Enhanced Verification Flow Component ─────────────────────────────── */

export const EnhancedVerificationFlow: React.FC = () => {
    const uid = useId();
    const role = getAppUserRole();
    const [restoredDraft] = useState<EnhancedVerificationDraft | null>(() =>
        readEnhancedVerificationDraftFromStorage(),
    );
    const [draftRestored, setDraftRestored] = useState(restoredDraft !== null);

    const [flowState, setFlowState] = useState<EnhancedFlowState>({
        step: 'upload',
        imageFile: null,
        textInput: restoredDraft?.textInput ?? '',
        errors: {},
        apiError: null,
        result: null,
        evidenceArtifact: null,
        showArtifactViewer: false,
    });

    const [selectedTool, setSelectedTool] = useState<RedactionTool>({
        type: 'blackout',
        reason: 'Manual redaction',
    });

    const pendingPayload = useRef<FormData | null>(null);
    const { imageFile, textInput } = flowState;

    /* ── Reset Flow ───────────────────────────────────────────────────────── */

    // eslint-disable-next-line react-hooks/preserve-manual-memoization
    const resetFlow = useCallback(() => {
        setFlowState({
            step: 'upload',
            imageFile: null,
            textInput: '',
            errors: {},
            apiError: null,
            result: null,
            evidenceArtifact: null,
            showArtifactViewer: false,
        });
        setDraftRestored(false);
        if (typeof window !== 'undefined') {
            window.localStorage.removeItem(ENHANCED_DRAFT_STORAGE_KEY);
        }
        pendingPayload.current = null;
    }, []);

    useEffect(() => {
        if (typeof window === 'undefined' || flowState.step !== 'upload') return;
        const trimmedText = flowState.textInput.trim();
        if (trimmedText.length === 0) {
            window.localStorage.removeItem(ENHANCED_DRAFT_STORAGE_KEY);
            return;
        }
        window.localStorage.setItem(
            ENHANCED_DRAFT_STORAGE_KEY,
            JSON.stringify({ textInput: flowState.textInput }),
        );
    }, [flowState.step, flowState.textInput]);

    /* ── PII Detection (enhanced) ───────────────────────────────────────────── */

    const detectPII = useCallback((text: string): PiiDetectionResult => {
        const patterns = [
            { label: 'email address', pattern: /[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}/ },
            { label: 'phone number', pattern: /\+\d[\d\s\-.()*#]{5,}|\b\d{2,}[\s\-.]\d[\d\s\-.]{3,}\d/ },
            { label: 'national ID or SSN', pattern: /\b\d{9,12}\b/ },
        ];

        for (const { label, pattern } of patterns) {
            if (pattern.test(text)) {
                return { detected: true, type: label };
            }
        }
        return { detected: false };
    }, []);

    /* ── Form Validation ──────────────────────────────────────────────────── */

    const validateUploadForm = useCallback((
        imageFile: File | null,
        text: string
    ): ValidationErrors => {
        const errors: ValidationErrors = {};
        const hasImage = imageFile !== null;
        const trimmedText = text.trim();
        const hasText = trimmedText.length > 0;

        if (!hasImage && !hasText) {
            errors.form = 'Please provide at least one piece of evidence — an image or a text description.';
            return errors;
        }

        if (hasImage) {
            if (!ACCEPTED_MIME_SET.has(imageFile.type)) {
                errors.image = 'Only PNG, JPEG, and WebP images are accepted.';
            } else if (imageFile.size > MAX_IMAGE_BYTES) {
                errors.image = 'Image must be 5 MB or smaller.';
            }
        }

        if (hasText && trimmedText.length < MIN_TEXT_LENGTH) {
            errors.text = `Text evidence must be at least ${MIN_TEXT_LENGTH} characters long.`;
        }

        return errors;
    }, []);

    /* ── Form Submission ───────────────────────────────────────────────────── */

    // eslint-disable-next-line react-hooks/preserve-manual-memoization
    const handleSubmit = useCallback(async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        
        // 1. Client-side validation
        const validationErrors = validateUploadForm(imageFile, textInput);
        if (Object.keys(validationErrors).length > 0) {
            setFlowState(prev => ({ ...prev, errors: validationErrors }));
            return;
        }

        // 2. PII detection
        const trimmedText = textInput.trim();
        const piiResult = detectPII(trimmedText);
        if (piiResult.detected) {
            setFlowState(prev => ({
                ...prev,
                errors: {
                    text: `Your text appears to contain a ${piiResult.type}. Please remove it or proceed with redaction.`,
                },
            }));
            return;
        }

        // 3. Create evidence artifact
        const evidenceArtifact = createMockEvidenceArtifact(imageFile, trimmedText, false);
        
        // 4. Build FormData
        const form = new FormData();
        if (imageFile) {
            form.append('image', imageFile);
        }
        if (trimmedText.length > 0) {
            form.append('text', trimmedText);
        }
        pendingPayload.current = form;

        // 5. Update state and show artifact viewer
        setFlowState(prev => ({
            ...prev,
            errors: {},
            apiError: null,
            evidenceArtifact,
            showArtifactViewer: true,
            step: 'analysing',
        }));
    }, [imageFile, textInput, validateUploadForm, detectPII]);

    /* ── API Verification ─────────────────────────────────────────────────── */

    useEffect(() => {
        if (flowState.step !== 'analysing' || !pendingPayload.current) return;

        let cancelled = false;

        startEvidenceVerification(pendingPayload.current)
            .then((data) => {
                if (cancelled) return;
                setFlowState(prev => ({
                    ...prev,
                    result: data,
                    step: 'result',
                }));
            })
            .catch((err: unknown) => {
                if (cancelled) return;
                if (err instanceof VerificationApiError) {
                    setFlowState(prev => ({ ...prev, apiError: err.message, step: 'upload' }));
                } else {
                    setFlowState(prev => ({
                        ...prev,
                        apiError: 'An unexpected error occurred. Please try again.',
                        step: 'upload',
                    }));
                }
                pendingPayload.current = null;
            });

        return () => {
            cancelled = true;
        };
    }, [flowState.step]);

    /* ── Redaction Handlers ───────────────────────────────────────────────── */

    // eslint-disable-next-line react-hooks/preserve-manual-memoization
    const handleRedactionChange = useCallback((regions: RedactionRegion[]) => {
        if (!flowState.evidenceArtifact) return;

        const updatedArtifact = {
            ...flowState.evidenceArtifact,
            redactionState: {
                ...flowState.evidenceArtifact.redactionState,
                regions,
                lastModified: new Date(),
                modifiedBy: 'current-user',
            },
        };

        setFlowState(prev => ({ ...prev, evidenceArtifact: updatedArtifact }));
    }, [flowState.evidenceArtifact]);

    // eslint-disable-next-line react-hooks/preserve-manual-memoization
    const handleArtifactUpdate = useCallback((artifact: EvidenceArtifact) => {
        setFlowState(prev => ({ ...prev, evidenceArtifact: artifact }));
    }, []);

    // eslint-disable-next-line react-hooks/preserve-manual-memoization
    const handleRedactionLevelChange = useCallback((level: RedactionLevel) => {
        if (!flowState.evidenceArtifact) return;

        const updatedArtifact = {
            ...flowState.evidenceArtifact,
            redactionState: {
                ...flowState.evidenceArtifact.redactionState,
                level,
                lastModified: new Date(),
                modifiedBy: 'current-user',
            },
        };

        setFlowState(prev => ({ ...prev, evidenceArtifact: updatedArtifact }));
    }, [flowState.evidenceArtifact]);

    const handleAutoRedaction = useCallback(() => {
        if (!flowState.evidenceArtifact) return;

        // Mock auto-redaction - in real implementation this would call an API
        const mockRegions: RedactionRegion[] = [
            {
                id: `auto-${Date.now()}`,
                x: 10,
                y: 10,
                width: 30,
                height: 10,
                reason: 'Auto-detected email address',
                createdAt: new Date(),
                createdBy: 'system',
            },
        ];

        handleRedactionChange([...flowState.evidenceArtifact.redactionState.regions, ...mockRegions]);
    }, [flowState.evidenceArtifact, handleRedactionChange]);

    const handleClearAllRedactions = useCallback(() => {
        handleRedactionChange([]);
    }, [handleRedactionChange]);

    /* ── Derived IDs ───────────────────────────────────────────────────────── */

    const imageInputId = `${uid}-image`;
    const imageErrorId = `${uid}-image-error`;
    const textInputId = `${uid}-text`;
    const textErrorId = `${uid}-text-error`;
    const formErrorId = `${uid}-form-error`;

    /* ── Render ───────────────────────────────────────────────────────────── */

    return (
        <div className="p-6 bg-white dark:bg-gray-900 rounded-xl shadow-lg border border-gray-100 dark:border-gray-800">
            {/* Upload Step */}
            {flowState.step === 'upload' && (
                <div>
                    <h2 className="text-lg font-semibold mb-4">Submit Evidence for Verification</h2>

                    {!flowState.imageFile && flowState.textInput.trim().length === 0 && (
                        <div className="mb-6">
                            <AppEmptyState
                                compact
                                eyebrow="No Evidence Added"
                                title={
                                    isOperationsRole(role)
                                        ? 'Seed the review flow with sample evidence'
                                        : 'Start with sample evidence if you want to explore before submitting real details'
                                }
                                description={
                                    isOperationsRole(role)
                                        ? 'This enhanced flow is easiest to review with a short sample note and a small image so contributors can inspect upload, redaction, and result states.'
                                        : 'You can provide your own text and image, or insert sample evidence to learn the flow safely.'
                                }
                                actions={[
                                    {
                                        onClick: () => setFlowState(prev => ({ ...prev, textInput: getSampleVerificationText(role) })),
                                        label: 'Insert sample evidence',
                                        icon: 'sample',
                                    },
                                    { href: '/help', label: 'View help', icon: 'docs', variant: 'secondary' },
                                ]}
                            />
                        </div>
                    )}
                    
                    {flowState.apiError && (
                        <div
                            role="alert"
                            className="mb-4 p-3 rounded-lg border border-red-200 bg-red-50 text-red-700 dark:border-red-800 dark:bg-red-950/40 dark:text-red-300 text-sm"
                        >
                            {flowState.apiError}
                        </div>
                    )}

                    {draftRestored && (
                        <p className="mb-4 rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs text-blue-700 dark:border-blue-800 dark:bg-blue-950/30 dark:text-blue-200">
                            Restored your locally saved draft from this device.
                        </p>
                    )}

                    {flowState.errors.form && (
                        <p
                            id={formErrorId}
                            role="alert"
                            className="mb-3 text-sm text-red-500 dark:text-red-400"
                        >
                            {flowState.errors.form}
                        </p>
                    )}

                    <form onSubmit={handleSubmit} noValidate aria-label="Evidence upload form">
                        {/* Image Upload */}
                        <div className="mb-4">
                            <label
                                htmlFor={imageInputId}
                                className="block text-sm font-medium mb-1"
                            >
                                Evidence image{' '}
                                <span className="text-gray-400 dark:text-gray-500 font-normal">
                                    (PNG, JPEG, or WebP — max 5 MB)
                                </span>
                            </label>
                            <input
                                id={imageInputId}
                                type="file"
                                accept="image/png,image/jpeg,image/webp"
                                aria-describedby={flowState.errors.image ? imageErrorId : undefined}
                                aria-invalid={!!flowState.errors.image}
                                onChange={(e) => {
                                    const file = e.target.files?.[0] ?? null;
                                    setFlowState(prev => ({ ...prev, imageFile: file }));
                                }}
                                className="block w-full text-sm text-gray-700 dark:text-gray-300 file:mr-3 file:py-1.5 file:px-3 file:rounded-md file:border-0 file:text-sm file:font-medium file:bg-gray-100 file:text-gray-700 hover:file:bg-gray-200 dark:file:bg-gray-800 dark:file:text-gray-300 dark:hover:file:bg-gray-700 transition-colors cursor-pointer"
                            />
                            {flowState.imageFile && !flowState.errors.image && (
                                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                                    Selected: {flowState.imageFile.name}
                                </p>
                            )}
                            {flowState.errors.image && (
                                <span
                                    id={imageErrorId}
                                    role="alert"
                                    className="mt-1 block text-sm text-red-500 dark:text-red-400"
                                >
                                    {flowState.errors.image}
                                </span>
                            )}
                        </div>

                        {/* Text Evidence */}
                        <div className="mb-6">
                            <label
                                htmlFor={textInputId}
                                className="block text-sm font-medium mb-1"
                            >
                                Text evidence{' '}
                                <span className="text-gray-400 dark:text-gray-500 font-normal">
                                    (min. 20 characters — do not include personal identifying information)
                                </span>
                            </label>
                            <textarea
                                id={textInputId}
                                value={flowState.textInput}
                                onChange={(e) => setFlowState(prev => ({ ...prev, textInput: e.target.value }))}
                                rows={4}
                                aria-describedby={flowState.errors.text ? textErrorId : undefined}
                                aria-invalid={!!flowState.errors.text}
                                placeholder="Describe your situation or the evidence supporting your request…"
                                className="w-full rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-sm px-3 py-2 placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-y transition-colors"
                            />
                            {flowState.errors.text && (
                                <span
                                    id={textErrorId}
                                    role="alert"
                                    className="mt-1 block text-sm text-red-500 dark:text-red-400"
                                >
                                    {flowState.errors.text}
                                </span>
                            )}
                        </div>

                        <div className="flex flex-wrap items-center gap-3">
                            <button
                                type="submit"
                                disabled={!flowState.imageFile && flowState.textInput.trim().length === 0}
                                aria-disabled={!flowState.imageFile && flowState.textInput.trim().length === 0}
                                className="px-6 py-2.5 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                            >
                                Submit for Verification
                            </button>
                            <button
                                type="button"
                                onClick={resetFlow}
                                className="px-4 py-2 text-sm font-medium rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-100 dark:border-gray-700 dark:text-gray-200 dark:hover:bg-gray-800 transition-colors"
                            >
                                Discard Draft
                            </button>
                        </div>
                    </form>
                </div>
            )}

            {/* Artifact Viewer Step */}
            {flowState.step === 'analysing' && flowState.evidenceArtifact && (
                <div>
                    <div className="flex items-center justify-between mb-4">
                        <h2 className="text-lg font-semibold">Review Evidence & Apply Redactions</h2>
                        <button
                            onClick={() => setFlowState(prev => ({ ...prev, step: 'upload' }))}
                            className="px-4 py-2 text-sm border border-gray-300 dark:border-gray-700 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                        >
                            Back to Upload
                        </button>
                    </div>
                    
                    <EvidenceArtifactViewer
                        artifact={flowState.evidenceArtifact}
                        onRedactionChange={handleRedactionChange}
                        onArtifactUpdate={handleArtifactUpdate}
                        className="mb-4"
                    />
                    
                    <RedactionControls
                        artifact={flowState.evidenceArtifact}
                        isEditing={false} // Will be managed by the viewer component
                        selectedTool={selectedTool}
                        selectedRegions={[]} // Will be managed by the viewer component
                        onToggleEdit={() => {}}
                        onToolChange={setSelectedTool}
                        onRegionRemove={() => {}}
                        onRedactionLevelChange={handleRedactionLevelChange}
                        onAutoRedaction={handleAutoRedaction}
                        onClearAllRedactions={handleClearAllRedactions}
                    />
                    
                    <div className="mt-4 flex justify-end">
                        <button
                            onClick={() => setFlowState(prev => ({ ...prev, step: 'result' }))}
                            className="px-6 py-2.5 bg-green-600 text-white text-sm font-medium rounded-lg hover:bg-green-700 transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
                        >
                            Continue to Verification
                        </button>
                    </div>
                </div>
            )}

            {/* Analysis Step */}
            {flowState.step === 'analysing' && !flowState.evidenceArtifact && (
                <div className="flex flex-col items-center justify-center py-12 space-y-6">
                    <p className="text-lg font-semibold text-gray-800 dark:text-gray-200">
                        Analysing...
                    </p>
                    <div
                        role="progressbar"
                        aria-label="Analysing evidence…"
                        aria-valuemin={0}
                        aria-valuemax={100}
                        className="w-full max-w-sm h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"
                    >
                        <div className="h-full w-1/2 rounded-full bg-blue-500 animate-[slide_1.4s_ease-in-out_infinite]" />
                    </div>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                        Please wait while we analyse your evidence.
                    </p>
                </div>
            )}

            {/* Result Step */}
            {flowState.step === 'result' && flowState.result !== null && (
                <div className="space-y-6">
                    <h2 className="text-lg font-semibold">Verification Result</h2>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <div className="p-4 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800">
                            <p className="text-xs font-medium uppercase tracking-widest text-gray-400 dark:text-gray-500 mb-1">
                                Score
                            </p>
                            <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                                {String(flowState.result.score)}
                            </p>
                        </div>

                        <div className="p-4 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800">
                            <p className="text-xs font-medium uppercase tracking-widest text-gray-400 dark:text-gray-500 mb-1">
                                Risk Level
                            </p>
                            <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                                {String(flowState.result.risk_level)}
                            </p>
                        </div>
                    </div>

                    {flowState.evidenceArtifact && (
                        <div className="mt-4">
                            <h3 className="text-md font-medium mb-2">Evidence Summary</h3>
                            <div className="text-sm text-gray-600 dark:text-gray-400">
                                <p>• {flowState.evidenceArtifact.metadata.type} evidence submitted</p>
                                <p>• {flowState.evidenceArtifact.redactionState.regions.length} redaction(s) applied</p>
                                <p>• PII detected: {flowState.evidenceArtifact.metadata.piiDetected ? 'Yes' : 'No'}</p>
                            </div>
                        </div>
                    )}

                    <button
                        type="button"
                        onClick={resetFlow}
                        aria-label="Start a new verification"
                        className="px-6 py-2.5 border border-gray-300 dark:border-gray-700 text-sm font-medium rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-offset-2"
                    >
                        Start New Verification
                    </button>

                    <Link
                        href="/help"
                        className="inline-flex items-center rounded-lg text-sm font-medium text-blue-600 hover:text-blue-700"
                    >
                        Review contributor help
                    </Link>
                </div>
            )}
        </div>
    );
};
